<?php

namespace Wit\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdmissionSchedulerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionSchedulerRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}

	public function findAllActive()
	{
		return $this->getEntityManager()->createQuery('SELECT userlogs FROM ModelBundle:UserLogs userlogs WHERE userlogs.isActive=1 ORDER BY userlogs.id DESC')->getResult();
	}

	public function findOpenSchedule(){
        $currentSchedule = $this->getEntityManager()->createQuery("SELECT a FROM ModelBundle:AdmissionScheduler a WHERE a.isOpen=1")->setMaxResults(1)->getOneOrNullResult();
        return $currentSchedule;
	}

	public function findApplicationInCurrentSchedule($application_id){

		$criteria = new \Doctrine\Common\Collections\Criteria();
        $criteria
          ->orWhere($criteria->expr()->contains('isOpen', 1))
          ->setMaxResults(1);
        $admissionScheduler = $em->getRepository('ModelBundle:AdmissionScheduler')->matching($criteria);

	}

}
