<?php

namespace Wit\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaritalStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaritalStatusRepository extends EntityRepository
{
}
