<?php

namespace Wit\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLogsRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}

	public function findAllActive()
	{
		return $this->getEntityManager()->createQuery('SELECT userlogs FROM ModelBundle:UserLogs userlogs WHERE userlogs.isActive=1 ORDER BY userlogs.id DESC')->getResult();
	}

	// TODO: all below

	/*
		All logs for ROLE USER and ROLE USER specific users based on logs availability
	*/
	public function findLogsForUserRoleUsers(){

		$criteria = new \Doctrine\Common\Collections\Criteria();
        $criteria
          ->orWhere($criteria->expr()->contains('isForUser', 1))
          ->orWhere($criteria->expr()->contains('userRoleUserId', $this->getOnlineUserId()))
          ->orderBy(array("id" => $criteria::DESC))
          ->setFirstResult(0)
          ->setMaxResults(10);

        return $this->getEntityManager()->getRepository('ModelBundle:UserLogs')->matching($criteria);
	}

	/* get online user id */
	public function getOnlineUserId(){
		return $this->get('security.context')->getToken()->getUser()->getId();
	}
}
