# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#   login_listener:
#      class: 'Wit\AuthBundle\Listener\LoginListener'
#      arguments: ['@security.context', '@doctrine']
#      tags:
#         - { name: 'kernel.event_listener', event: 'security.interactive_login' }

   user_register_listener:
      class: 'Wit\UserBundle\Listener\RegisterListener'
      arguments: ['@service_container', '@router']
      tags:
         - { name: doctrine.event_listener, event: postPersist }

   user_application_listener:
      class: 'Wit\UserBundle\Listener\ApplicationListener'
      arguments: ['@service_container', '@router']
      tags:
         - { name: doctrine.event_listener, event: postPersist }

   # this services will be used to hold common / non-database user functions
   wit.helper.user:
      class: 'Wit\UserBundle\Helper\UserHelper'
      arguments: ['@service_container', '@router']
